[tool.poetry]
name = "ov-project"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
sentence-transformers = "^3.0.0"
langchain = "^0.2.2"
dotenv = "^0.0.5"
cohere = "^5.5.4"
streamlit = "^1.35.0"

[tool.poetry.group.dev.dependencies]
black = "^24.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
